name: tvOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
    - name: Run Test
      working-directory: MixpanelDemo
      run: |
        set -o pipefail
        xcodebuild -scheme MixpanelDemoTV -derivedDataPath Build/ -configuration Debug \
          -destination 'platform=tvOS Simulator,name=Apple TV' \
          ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES -enableCodeCoverage YES \
          clean build test | xcpretty -c
    - name: Code Coverage Report
      working-directory: MixpanelDemo/Build/Logs/Test
      run: |
        xcrun xccov view --report --files-for-target Mixpanel.framework  *.xcresult
        xcrun xccov view --report --only-targets *.xcresult
